projects:
  platform: 
    namespace: argocd
    description: Platform team project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        server: "*"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

  apps:
    namespace: argocd
    description: App team project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "!argocd"
        server: "*"
      - namespace: "!kube-system"
        server: "*"
    clusterResourceBlacklist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"  

applications:
  argocd-apps:
    project: platform
    source:
      repoURL: https://argoproj.github.io/argo-helm
      path: argocd-apps
      targetRevision: 2.0.0
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: true
      syncOptions:
        - CreateNamespace=true

  addons: 
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: argocd
    source:
      path: argocd/platform/addons
      repoURL: 'https://github.com/irizzante/externalsecrets-bitwarden.git'
      targetRevision: HEAD
    project: platform
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
        allowEmpty: true
      syncOptions:
        - CreateNamespace=true
