projects:
- name: platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  description: Platform team project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

- name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  description: App team project
  sourceRepos:
    - "https://production.eng.it/gitlab/dirseresl/aspi/"
  destinations:
    - namespace: "!argocd"
      server: "*"
    - namespace: "!kube-system"
      server: "*"
  clusterResourceBlacklist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"      

applications:

- name: addons
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    path: argocd/platform/addons
    repoURL: 'https://github.com/irizzante/externalsecrets-bitwarden.git'
    targetRevision: HEAD
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
