apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/irizzante/externalsecrets-bitwarden.git
          revision: HEAD
          files:
          - path: argocd/platform.yaml
      - list:
          elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      destination:
        namespace: '{{.namespace}}'
        name: '{{.destinationName}}'
      project: '{{.project}}'
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.version}}'
        path: '{{.path}}'
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
